<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-03-05 03:34
=======
# Generated by Django 5.1.4 on 2025-03-04 09:14
>>>>>>> b6ac95eb35fb62f79ae3cd6b11cea1b27ba8e150

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.businessunitsettings'),
        ),
    ]
