# Generated by Django 5.1.4 on 2025-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.JSONField()),
                ('gstin', models.CharField(max_length=100, null=True)),
                ('pan', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('applicable_to', models.CharField(max_length=50)),
                ('no_of_document', models.IntegerField()),
                ('expiry_date', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('identification', models.BooleanField()),
                ('issue_date', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_employee_profile', models.CharField(choices=[('allowed', 'allowed'), ('limited', 'limited'), ('blocked', 'blocked')], max_length=50)),
                ('unique_fields', models.JSONField()),
                ('employee_skills', models.CharField(choices=[('1-3', '1-3'), ('1-5', '1-5'), ('1-10', '1-10'), ('custom', 'custom')], max_length=50)),
                ('custom_skills', models.JSONField(blank=True, null=True)),
                ('approve_required', models.BooleanField(default=False)),
                ('employees_addable', models.BooleanField(default=False)),
                ('filter_search', models.BooleanField(default=False)),
                ('generally_showable_fields', models.JSONField(default={'email': False, 'employee_status': False, 'profile_image': False})),
                ('officially_showable_fields', models.JSONField(default={'department': False, 'designation': False, 'employee_code': False, 'joining_date': False, 'location': False, 'reporting_manager': False})),
                ('contacts_showable_fields', models.JSONField(default={'address': False, 'email': False, 'linked': False, 'mobile': False})),
                ('other_showable_fields', models.JSONField(default={'about_me': False, 'attendance_status': False, 'employment_type': False, 'service_status': False, 'skills': False})),
                ('mandatory_inputable_fields', models.JSONField(default={'bank_details': False, 'certifications': False, 'documents': False, 'education_details': False, 'emergency_contact': False, 'family_details': False, 'job_history': False, 'profile_image': False})),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.BooleanField(default=False, null=True)),
                ('aadhar', models.BooleanField(default=False, null=True)),
                ('job_history', models.BooleanField(default=False, null=True)),
                ('education', models.BooleanField(default=False, null=True)),
                ('family', models.BooleanField(default=False, null=True)),
                ('access_control', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
