# Generated by Django 5.1.4 on 2025-03-13 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bandssettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bands_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessunitsettings',
            name='unit_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_units_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessunitsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_units_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designationsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofilesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeesettings',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeesettings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
    ]
