# Generated by Django 5.1.4 on 2025-03-19 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('addedon', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_from_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('addedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_added_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AttendaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_attendance', models.BooleanField(default=True, null=True)),
                ('default_attendance_status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present')], default='absent', max_length=20, null=True)),
                ('deduct_salary_for_absent_days', models.CharField(default='yes', max_length=20, null=True)),
                ('company_start_time', models.TimeField(null=True)),
                ('company_end_time', models.TimeField(null=True)),
                ('hide_total_hours', models.BooleanField(default=False, null=True)),
                ('hide_attendance_punches', models.BooleanField(default=False, null=True)),
                ('disable_web_attendance', models.BooleanField(default=False, null=True)),
                ('enable_ip_restrictions', models.BooleanField(default=False, null=True)),
                ('disable_mobile_attendance', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_attendance_unit', models.BooleanField(default=False)),
                ('number_of_unit_for_absent', models.IntegerField(default=1, null=True)),
                ('deduct_break_hours', models.BooleanField(default=False, null=True)),
                ('daily_auto_attendance_calculation', models.BooleanField(default=True, null=True)),
                ('enable_leave_based_rules', models.BooleanField(default=True, null=True)),
                ('auto_assign_shift', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CompensationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_eligiibility', models.CharField(max_length=100, null=True)),
                ('weekoff_eligiibility', models.CharField(max_length=100, null=True)),
                ('holiday_eligiibility', models.CharField(max_length=100, null=True)),
                ('daily_rule', models.JSONField(null=True)),
                ('weekoff_rule', models.JSONField(null=True)),
                ('holiday_rule', models.JSONField(null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CompOffRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_eligiibility', models.CharField(max_length=100, null=True)),
                ('weekoff_eligiibility', models.CharField(max_length=100, null=True)),
                ('holiday_eligiibility', models.CharField(max_length=100, null=True)),
                ('daily_rule', models.JSONField(null=True)),
                ('weekoff_rule', models.JSONField(null=True)),
                ('holiday_rule', models.JSONField(null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RegularizationPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_justify_punch', models.BooleanField(default=False, null=True)),
                ('restrict_attendance_justification_days', models.IntegerField(default=0, null=True)),
                ('enable_request_punch', models.BooleanField(default=False, null=True)),
                ('enable_multiple_punches', models.BooleanField(default=False, null=True)),
                ('restrict_punch_request_days', models.IntegerField(default=0, null=True)),
                ('punch_approval_status', models.CharField(choices=[('Manager Approved', 'Manager Approved'), ('Approved', 'Approved')], default='Manager Approved', max_length=20, null=True)),
                ('restrict_duty_punch_employee', models.IntegerField(default=0, null=True)),
                ('restrict_real_time_justify_employee', models.IntegerField(default=0, null=True)),
                ('restrict_punch_request_manager', models.IntegerField(default=0, null=True)),
                ('restrict_attendance_approval_manager', models.IntegerField(default=0, null=True)),
                ('restrict_late_justify_manager', models.IntegerField(default=0, null=True)),
                ('restrict_early_exit_justify_manager', models.IntegerField(default=0, null=True)),
                ('restrict_total_time_justify_manager', models.IntegerField(default=0, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RosterShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_roster_shifts', models.BooleanField(default=False, null=True)),
                ('allow_managers_assign_shifts', models.BooleanField(default=False, null=True)),
                ('restrict_shift_change_days', models.PositiveIntegerField(default=0, null=True)),
                ('restrict_week_off_per_month', models.PositiveIntegerField(default=1, null=True)),
                ('restrict_week_off_per_week', models.PositiveIntegerField(default=1, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SandwichRulesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_sandwich_rules', models.BooleanField(default=False, null=True)),
                ('week_off_holidays_between_absents', models.BooleanField(default=False, null=True)),
                ('week_off_holidays_after_absent', models.BooleanField(default=False, null=True)),
                ('week_off_holidays_before_absent', models.BooleanField(default=False, null=True)),
                ('absent_week_offs_holidays_beginning_month', models.BooleanField(default=False, null=True)),
                ('absent_week_offs_holidays_end_month', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Flexible', 'Flexible')], max_length=100, null=True)),
                ('shift_code', models.CharField(max_length=100, null=True)),
                ('shift_title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('timein', models.TimeField(null=True)),
                ('timeout', models.TimeField(null=True)),
                ('make_default_shift', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftChangeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_employee_shift_change_request', models.BooleanField(default=False, null=True)),
                ('enable_manager_approval', models.BooleanField(default=False, null=True)),
                ('default_approval_status', models.CharField(choices=[('Manager Approved', 'Manager Approved'), ('Approved', 'Approved')], default='Pending', max_length=20, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TimeManagementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_overtime', models.BooleanField(default=False, null=True)),
                ('overtime_approval_status', models.CharField(choices=[('Manager Approved', 'Manager Approved'), ('Approved', 'Approved')], default='Manager Approved', max_length=20, null=True)),
                ('round_off_minutes', models.BooleanField(default=False, null=True)),
                ('rounding_method', models.CharField(choices=[('Standard', 'Standard'), ('Ceiling', 'Ceiling'), ('Floor', 'Floor'), ('No_Round_Off', 'No Round Off')], default='Standard', max_length=20, null=True)),
                ('rounding_value', models.IntegerField(default=1, null=True)),
                ('convert_overtime_to_compensation', models.BooleanField(default=False, null=True)),
                ('comp_off_request_on_overtime', models.BooleanField(default=False, null=True)),
                ('default_overtime_rule', models.CharField(choices=[('Compensation', 'Convert Approved Overtime into Compensation'), ('CompOff', 'Automatically raise CompOff request')], default='Compensation', max_length=20, null=True)),
                ('enable_undertime', models.BooleanField(default=False, null=True)),
                ('enable_attendance_rules', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UnderTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligiblity_hours', models.IntegerField(null=True)),
                ('consider_absent', models.BooleanField(default=False, null=True)),
                ('conside_half_day', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('all_weeks', models.BooleanField(default=False, null=True)),
                ('second_week', models.BooleanField(default=False, null=True)),
                ('fifth_week', models.BooleanField(default=False, null=True)),
                ('alternate_weeks', models.BooleanField(default=False, null=True)),
                ('all_but_last', models.BooleanField(default=False, null=True)),
                ('third_week', models.BooleanField(default=False, null=True)),
                ('last_two_weeks', models.BooleanField(default=False, null=True)),
                ('first_week', models.BooleanField(default=False, null=True)),
                ('fourth_week', models.BooleanField(default=False, null=True)),
                ('last_week', models.BooleanField(default=False, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
    ]
