# Generated by Django 5.1.4 on 2025-03-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_allowedip_attendacesettings_calculationpolicy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allowed_ip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_allowed_ip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendacesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendacesettings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendacesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attendacesettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calculation_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_calculation_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationrules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compensationrules',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensation_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationrules',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='compensationrules',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_compensation_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffrules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compoffrules',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comp_off_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffrules',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='compoffrules',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_comp_off_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regularization_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_regularization_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rostershiftsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rostershiftsettings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_shift_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rostershiftsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rostershiftsettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roster_shift_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sandwichrulessettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sandwichrulessettings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sandwich_rules_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sandwichrulessettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sandwichrulessettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sandwich_rules_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shift', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftchangesettings',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_change_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftchangesettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shift_change_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timemanagementpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timemanagementpolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_management_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timemanagementpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timemanagementpolicy',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_time_management_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='undertimerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='undertimerule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_under_time_rule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='undertimerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='undertimerule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_under_time_rule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyoff',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weekly_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyoff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyoff',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_weekly_off', to=settings.AUTH_USER_MODEL),
        ),
    ]
