# Generated by Django 5.1.4 on 2025-03-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_allowedip_created_at_allowedip_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='undertimerule',
            old_name='conside_half_day',
            new_name='consider_half_day',
        ),
        migrations.RenameField(
            model_name='undertimerule',
            old_name='eligiblity_hours',
            new_name='eligibility_hours',
        ),
    ]
