# Generated by Django 5.1.4 on 2025-03-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_conside_half_day_undertimerule_consider_half_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_attendance_rules', models.BooleanField(default=False)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rule', to='settings.shift')),
            ],
        ),
    ]
